I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 256, in script
    $ renpy.music.play("fireplace.mp3", channel="sound2", fadein=2.0, volume=0.7)
  File "game/script.rpy", line 256, in <module>
    $ renpy.music.play("fireplace.mp3", channel="sound2", fadein=2.0, volume=0.7)
TypeError: play() got an unexpected keyword argument 'volume'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 256, in script
    $ renpy.music.play("fireplace.mp3", channel="sound2", fadein=2.0, volume=0.7)
  File "D:\renpy-8.3.4-sdk\renpy\ast.py", line 827, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\renpy-8.3.4-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 256, in <module>
    $ renpy.music.play("fireplace.mp3", channel="sound2", fadein=2.0, volume=0.7)
TypeError: play() got an unexpected keyword argument 'volume'

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.4.24120703
Dancing With Shadows Alpha 1.0
Tue Mar 25 01:09:22 2025
