I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 41, in script
    image druidhouse1 = ("druidhouseP1.png", 1240, 1754)
Exception: Not a displayable: ('druidhouseP1.png', 1240, 1754)

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 41, in script
    image druidhouse1 = ("druidhouseP1.png", 1240, 1754)
  File "D:\renpy-8.3.4-sdk\renpy\ast.py", line 930, in execute
    renpy.exports.image(self.imgname, img)
  File "D:\renpy-8.3.4-sdk\renpy\exports\displayexports.py", line 73, in image
    d = renpy.easy.displayable(d)
  File "D:\renpy-8.3.4-sdk\renpy\easy.py", line 145, in displayable
    raise Exception("Not a displayable: %r" % (d,))
Exception: Not a displayable: ('druidhouseP1.png', 1240, 1754)

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.4.24120703
Dancing With Shadows Alpha 1.0
Mon Mar  3 15:04:09 2025
