I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 3249, in script
    "Rachel "Des" Marzzarella\\Lake Watkins\\Deniz Balik"
  File "renpy/common/00library.rpy", line 324, in say
    who(what, interact=interact, *args, **kwargs)
Exception: Say has image attributes ('Des',), but there's no image tag associated with the speaking character.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 3249, in script
    "Rachel "Des" Marzzarella\\Lake Watkins\\Deniz Balik"
  File "C:\Users\Rachel\Desktop\dances\dancingwithshadows\renpy\ast.py", line 2579, in execute
    Say.execute(self)
  File "C:\Users\Rachel\Desktop\dances\dancingwithshadows\renpy\ast.py", line 621, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\Rachel\Desktop\dances\dancingwithshadows\renpy\exports\sayexports.py", line 130, in say
    renpy.store.say(who, what, *args, **kwargs)
  File "renpy/common/00library.rpy", line 324, in say
    who(what, interact=interact, *args, **kwargs)
  File "C:\Users\Rachel\Desktop\dances\dancingwithshadows\renpy\character.py", line 1393, in __call__
    old_attr_state = self.handle_say_attributes(False, interact)
  File "C:\Users\Rachel\Desktop\dances\dancingwithshadows\renpy\character.py", line 1212, in handle_say_attributes
    if self.resolve_say_attributes(predicting, attrs):
  File "C:\Users\Rachel\Desktop\dances\dancingwithshadows\renpy\character.py", line 1138, in resolve_say_attributes
    raise Exception("Say has image attributes %r, but there's no image tag associated with the speaking character." % (attrs,))
Exception: Say has image attributes ('Des',), but there's no image tag associated with the speaking character.

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.4.24120703
Dancing With Shadows Alpha 1.0
Fri Feb 21 12:50:30 2025
