I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 314, in script
    {i}"Magicians of any kind make me nervous. He seems friendly enough, but I shouldn't let my guard down."
Exception: Sayer b'{i}' is not a function or string.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 314, in script
    {i}"Magicians of any kind make me nervous. He seems friendly enough, but I shouldn't let my guard down."
  File "C:\Users\Rachel\Desktop\dances\dancingwithshadows\renpy\ast.py", line 2579, in execute
    Say.execute(self)
  File "C:\Users\Rachel\Desktop\dances\dancingwithshadows\renpy\ast.py", line 598, in execute
    raise Exception("Sayer %s is not a function or string." % self.who.encode("utf-8"))
Exception: Sayer b'{i}' is not a function or string.

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.4.24120703
Dancing With Shadows Prologue 1.0
Fri Apr 18 03:52:14 2025
