I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 1426, in script
    with disolve
  File "game/script.rpy", line 1426, in <module>
    with disolve
NameError: name 'disolve' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 1426, in script
    with disolve
  File "C:\Users\Rachel\Desktop\dances\dancingwithshadows\renpy\ast.py", line 1360, in execute
    trans = renpy.python.py_eval(self.expr)
  File "C:\Users\Rachel\Desktop\dances\dancingwithshadows\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Rachel\Desktop\dances\dancingwithshadows\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 1426, in <module>
    with disolve
NameError: name 'disolve' is not defined

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.4.24120703
Dancing With Shadows Alpha 1.0
Thu Feb 27 22:53:22 2025
