I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 1554, in script
    Play sound "040436_climbing-a-ladder-79239.wav"
TypeError: __init__() missing 1 required positional argument: 'file'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 1554, in script
    Play sound "040436_climbing-a-ladder-79239.wav"
  File "C:\Users\Rachel\Desktop\dances\dancingwithshadows\renpy\ast.py", line 2579, in execute
    Say.execute(self)
  File "C:\Users\Rachel\Desktop\dances\dancingwithshadows\renpy\ast.py", line 621, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\Rachel\Desktop\dances\dancingwithshadows\renpy\exports\sayexports.py", line 132, in say
    who(what, *args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'file'

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.4.24120703
Dancing With Shadows Alpha 1.0
Sat Mar 29 01:33:17 2025
