I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 243, in script
    with longdissovle
  File "game/script.rpy", line 243, in <module>
    with longdissovle
NameError: name 'longdissovle' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 243, in script
    with longdissovle
  File "D:\renpy-8.3.4-sdk\renpy\ast.py", line 1360, in execute
    trans = renpy.python.py_eval(self.expr)
  File "D:\renpy-8.3.4-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "D:\renpy-8.3.4-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 243, in <module>
    with longdissovle
NameError: name 'longdissovle' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.4.24120703
Dancing With Shadows Alpha 1.0
Mon Mar 24 23:19:30 2025
